version: '3'
services:
  web:
    container_name: flask_chatbot
    build: .
    ports:
     - "${PORT}:5000"
    volumes:
      - .:/app
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  ngnix:
    container_name: nginx_chatbot
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - "web"